### ISSUE TITLE
TypeError: CustomResource.__init__() got an unexpected keyword argument 'package'

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#16775]
### What happened?

When attempting to use parameterized providers on Python's `pulumi v1.126.0` package, I get the following error:

```
𝛌 pulumi up
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/pulumi/ian-test-python/dev/previews/d6b9a096-e136-4627-8078-f6232666409f

Loading policy packs...

     Type                 Name                 Plan       Info
 +   pulumi:pulumi:Stack  ian-test-python-dev  create     1 error; 3 messages

Policies:
    ✅ pulumi-internal-policies@v0.0.6

Diagnostics:
  pulumi:pulumi:Stack (ian-test-python-dev):
    /Users/ianwahbe/Projects/pulumi/langs/python/random/python/pulumi_random/pet.py:222: RuntimeWarning: coroutine 'get_package' was never awaited
      super(Pet, __self__).__init__(
    RuntimeWarning: Enable tracemalloc to get the object allocation traceback

    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/ianwahbe/Projects/pulumi/langs/python/./__main__.py", line 25, in <module>
        pet = random.Pet("hi", length=3, separator="-")
      File "/Users/ianwahbe/Projects/pulumi/langs/python/random/python/pulumi_random/pet.py", line 200, in __init__
        __self__._internal_init(resource_name, *args, **kwargs)
      File "/Users/ianwahbe/Projects/pulumi/langs/python/random/python/pulumi_random/pet.py", line 222, in _internal_init
        super(Pet, __self__).__init__(
    TypeError: CustomResource.__init__() got an unexpected keyword argument 'package'
```

This works on the v1.125.0 SDK.

### Example

Checkout https://github.com/iwahbe/pulumi-python-repros/tree/2202a6fa4c49554ec43575041b45accc144790dc and run `pulumi up`.

### Output of `pulumi about`

```
CLI          
Version      3.125.0-dev.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME           VERSION
resource  pinecone       0.4.1
resource  pulumi_alz     0.11.1
resource  pulumi_random  3.6.2
language  python         unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in python: executable='/Users/ianwahbe/Projects/pulumi/langs/python/venv/bin/python' version='3.10.11'

Current Stack: pulumi/ian-test-python/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ian-pulumi-corp
User           ian-pulumi-corp
Organizations  ian-pulumi-corp, pulumi
Token type     personal

Dependencies:
NAME             VERSION
deepdiff         6.2.1
pinecone-pulumi  0.4.1
pip              24.1.2
pulumi_alz       0.11.1
pulumi_random    3.6.2
requests         2.28.1
setuptools       70.3.0
wheel            0.43.0

Pulumi locates its logs in /var/folders/fg/_1q36r4j6yx0rwz2fbhjd5y40000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
OK this is expected. We renamed that parameter from "package" to "packageRef". The SDK and codegen in 3.126.0 _should_ match, so this was probably a case of a new SDK but still using the old python codegen.

Again I've mentioned a few times, but we don't consider this "stable" yet so we're taking the opportunity to make break changes.

**Comment by iwahbe** [comment]
That is the case. I forgot that I needed to re-install the python plugin, in addition to the SDK to get everything working again.
