### ISSUE TITLE
v3.194.0 of the `pkg` go module does not work with v3.194.0 of the `sdk` module

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#20487]
When trying to upgrade pulumi `pkg` and `sdk` modules to v3.194.0:

```
require (
	github.com/pulumi/pulumi/pkg/v3 v3.194.0
	github.com/pulumi/pulumi/sdk/v3 v3.194.0
)
```

you'll get errors like:

```
Error: /home/runner/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.194.0/resource/deploy/source.go:139:26: undefined: resource.StackFrame
Error: /home/runner/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.194.0/resource/deploy/source_eval.go:503:4: unknown field StackTrace in struct literal of type resource.NewGoal
Error: /home/runner/go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.194.0/resource/deploy/source_eval.go:1796:30: undefined: resource.StackFrame
...
```

Here's what happened: there was a time window between when `sdk/v3.194.0` and `pkg/v3.194.0` were tagged, and a [commit](https://github.com/pulumi/pulumi/commit/cb6c33b51efa04940b645cb0d3d4c18d2a112e3f) merged in that window that made changes to both `sdk` and `pkg` with `pkg` depending on the changes in `sdk`. So now we’re in a place where `pkg/v3.194.0` is depending on things in `sdk` that haven’t released yet.

We should tag new versions of `sdk` and `pkg` that don't have this problem, and consider [retracting](https://go.dev/ref/mod#go-mod-file-retract) v3.194.0 of these modules.

**Comment by justinvp** [comment]
Fixed by https://github.com/pulumi/pulumi/releases/tag/v3.195.0
