### ISSUE TITLE
Pulumi providers fail on Python 3.11.9

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#15882]
### What happened?

When upgrading from Python 3.11.8 to Python 3.11.9 Pulumi Python programs written against stock providers such as pulumi-aws start failing.

### Example

https://github.com/t0yv0/test-pyversion/actions/runs/8618012070/job/23619367836#step:5:112

```
Diagnostics:
  pulumi:pulumi:Stack (test-pyversion-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/home/runner/work/test-pyversion/test-pyversion/__main__.py", line 6, in <module>
        pulumi.export('v', ami.get_linux_ami(ty))
                           ^^^^^^^^^^^^^^^^^^^^^
      File "/home/runner/work/test-pyversion/test-pyversion/ami.py", line 148, in get_linux_ami
        region = config.region
                 ^^^^^^^^^^^^^
      File "<frozen importlib.util>", line 276, in __getattribute__
    AttributeError: module 'pulumi_aws.config' has no attribute 'region'
```

```
from pulumi_aws import config
print(config.region)
```

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
We should also check other recent [releases](https://www.python.org/downloads/) (3.12.3, 3.10.14, 3.9.19, and 3.8.19)

**Comment by justinvp** [comment]
Possibly due to https://github.com/python/cpython/commit/46f821d62b5a1599890419aa963d7353619942b6

Rather than setting `__class__` like [this](https://github.com/pulumi/pulumi-aws/blob/master/sdk/python/pulumi_aws/config/__init__.py):

```python
import sys
from .vars import _ExportableConfig

sys.modules[__name__].__class__ = _ExportableConfig
```

we may need to switch to the approach mentioned here: https://stackoverflow.com/a/18262696/43620

> Basically, subclass `types.ModuleType` and override `__getattr__` to import on demand.

**Comment by lunaris** [comment]
An update on this:

* I've taken Anton's example and reproduced it without Pulumi/Pulumi AWS code using just the lazy loader code from our Python SDK (`sdk/python/lib/pulumi/_utils.py`) at https://github.com/lunaris/python-lazy-loading-repro.
* As expected it works with 3.11.8 and breaks with 3.11.9. It also breaks with 3.12.3 (but works on 3.12.0, 3.12.1 and 3.12.2).
* This appears to be something that upstream has been spotted and potentially fixed (https://github.com/python/cpython/pull/117185, fixing https://github.com/python/cpython/issues/117182), though it's not super clear which (if any) versions fixes will be backported to. I've responded to what I believe is the fixing PR at https://github.com/python/cpython/pull/117185#issuecomment-2060851286 requesting backports.

All this said, we may be left with broken versions, in which case a couple of options I can see are:

* Detect broken versions and print warnings/terminate the Python process
* Update version bounds to single out and refuse to work on broken versions

**Comment by Frassle** [comment]
> Detect broken versions and print warnings/terminate the Python process

I think we can update the python language host to detect and log a loud warning for these bad versions. If the bad version of Python is still usable for some pulumi programs that's probably better then just error quitting. If basically no pulumi programs will work with those versions of python then let's just error out quickly on Run.

**Comment by justinvp** [comment]
> If basically no pulumi programs will work with those versions of python then let's just error out quickly on Run.

We could also consider excluding the broken versions from `python_requires`:

https://github.com/pulumi/pulumi/blob/f6b405c24ebc03f293173763ac93a75eacee5d8e/sdk/python/lib/setup.py#L43
