### ISSUE TITLE
Breaking Windows builds on feature-3.0 - tsc test failure

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#6614]
```
     1>Done building target "TestDependencies" in project "build.proj".
     1>Target "TestBuild" in project "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (target "BuildTests" depends on it):
       Task "Exec"
         yarn run tsc
         yarn run v1.22.10
     1>EXEC : warning package.json: No license field [D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj]
         $ D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\tests\integration\construct_component\testcomponent\node_modules\.bin\tsc
         ../../../../../../../../../../../Pulumi/node_modules/@pulumi/pulumi/automation/localWorkspace.d.ts:1:25 - error TS7016: Could not find a declaration file for module 'semver'. 'D:/Pulumi/node_modules/@pulumi/pulumi/node_modules/semver/semver.js' implicitly has an 'any' type.
           Try `npm install @types/semver` if it exists or add a new declaration (.d.ts) file containing `declare module 'semver';`
         1 import * as semver from "semver";
                                   ~~~~~~~~
         Found 1 error.
         error Command failed with exit code 2.
         info Visit yarnpkg.com/en/docs/cli/run for documentation about this command.
     1>D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj(286,5): error MSB3073: The command "yarn run tsc" exited with code 2.
       Done executing task "Exec" -- FAILED.
     1>Done building target "TestBuild" in project "build.proj" -- FAILED.
     1>Done Building Project "D:\a\pulumi\pulumi\src\github.com\pulumi\pulumi\build.proj" (Tests target(s)) -- FAILED.
```
