### ISSUE TITLE
v3.221.0 hangs when loading policies

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#21887]
Tracking this separately from https://github.com/pulumi/pulumi/issues/21864

## User Report

From https://github.com/pulumi/pulumi/issues/21864#issuecomment-3922758979:

> `3.221.0` hangs forever on the "Updating policy packs" message when running `pulumi preview` and I need to either `kill -9` the process from another window (`^c` does not do the job, nor does a mere `SIGTERM`) or kill the `pulumi-language-nodejs` process which causes the `pulumi preview` to exit.
> 
> Reverting to `3.220.0` fixes this. Seems like the new policy-pack code has issues.

## Root Cause

This regressed with https://github.com/pulumi/pulumi/pull/21684.

From https://github.com/pulumi/pulumi/issues/21864#issuecomment-3922973013:

> I've identified the root-cause of the hang (not sure if it'll also address the "Cannot find module" errors):
> 
> In the proxy, we call `client.ConfigureStack`:
> 
> https://github.com/pulumi/pulumi/blob/a4d809bf0146922560433b7d00fbd797d2c76d1a/sdk/policy_proxy.go#L151-L154
> 
> However, policy SDKs prior to v1.19.0 did not implement `ConfigureStack` and that call in the proxy is not gracefully handling gRPC Unimplemented errors.
> 
> The implementation in the proxy should look similar to this:
> 
> https://github.com/pulumi/pulumi/blob/a4d809bf0146922560433b7d00fbd797d2c76d1a/sdk/go/common/resource/plugin/analyzer_plugin.go#L257-L268
> 
> Additionally, if `ConfigureStack` errors for any other reason, we need to call `p.client.Reject(err)` to avoid hanging waiting for the client to be fulfilled.

## Resolution

This was fixed by https://github.com/pulumi/pulumi/pull/21866 and shipped in [v3.222.0](https://github.com/pulumi/pulumi/releases/tag/v3.222.0).
