### ISSUE TITLE
undefined: CFTypeLoggingConfig in Pulumi Golang v4@v4.3.1

### ISSUE THREAD

**Issue by athensofamerica** [pulumi/pulumi#7073]
When I try to provision AWS EKS with latest Pulumi golang SDK, the pulumi up failed with the following error:

error: an unhandled error occurred: program exited with non-zero exit code: 2

## Expected behavior

Expect EKS cluster to be successfully provisioned 

## Current behavior

The program aborted with the following errors:

error: an unhandled error occurred: program exited with non-zero exit code: 2

# github.com/pulumi/pulumi-aws/sdk/v4/go/aws/cloudformation
../../go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v4@v4.3.1/go/aws/cloudformation/cftype.go:39:16: undefined: CFTypeLoggingConfigPtrOutput
../../go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v4@v4.3.1/go/aws/cloudformation/cftype.go:110:17: undefined: CFTypeLoggingConfig
../../go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v4@v4.3.1/go/aws/cloudformation/cftype.go:147:16: undefined: CFTypeLoggingConfigPtrInput
../../go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v4@v4.3.1/go/aws/cloudformation/cftype.go:176:17: undefined: CFTypeLoggingConfig
../../go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v4@v4.3.1/go/aws/cloudformation/cftype.go:190:16: undefined: CFTypeLoggingConfigPtrInput
../../go/pkg/mod/github.com/pulumi/pulumi-aws/sdk/v4@v4.3.1/go/aws/cloudformation/getCFType.go:76:19: undefined: GetCFTypeLoggingConfig
## Steps to reproduce

This is the code snippet that I use to provision an EKS which caused the errors above:
import (
	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws"
	awseks "github.com/pulumi/pulumi-aws/sdk/v4/go/aws/eks"
	"github.com/pulumi/pulumi-eks/sdk/go/eks"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

		clusterArgs := &eks.ClusterArgs{
			ProviderCredentialOpts: eks.KubeconfigOptionsArgs{ProfileName: pulumi.StringPtr(profile)},
			DesiredCapacity:        pulumi.IntPtr(desiredCapacity),
			MinSize:                pulumi.IntPtr(minSize),
			MaxSize:                pulumi.IntPtr(maxSize),
			InstanceType:           pulumi.StringPtr(instanceType),
			VpcId:                  vpc.ID,
			PrivateSubnetIds:       vpc.Args.PrivateSubnets,
			PublicSubnetIds:        vpc.Args.PublicSubnets,
			EnabledClusterLogTypes: goStringArrayToPulumiStringArray(eksConfig.ClusterLogTypes),
			Version:                pulumi.StringPtr(eksConfig.K8sVersion),
			CreateOidcProvider:     pulumi.BoolPtr(true),
		}

		// Create an EKS cluster with the given configuration.
		cluster, err := eks.NewCluster(ctx, eksConfig.ClusterName, clusterArgs)
		if err != nil {
			fmt.Println("Create EKS cluster failure: ", err.Error())
			return err
		}

## Context (Environment)

Try to provision our EKS cluster. It used to work with pulumi 2.0. We are not longer to be able to provision EKS with 3.0 upgrade. This because a show stop unless we downgrade back to pulumi 2.0

## Affected feature
EKS provisioning
