### ISSUE TITLE
`pulumi.get_organization` returns `None` instead of returning org name

### ISSUE THREAD

**Issue by smithrobs** [pulumi/pulumi#18768]
### What happened?

In v3.152.0, for at least Python, `pulumi_org = pulumi.get_organization()` returned the organization name related to the program's stack.

In v3.153.0, it returns `None` even if the stack is part of an org.

### Example

```python
import pulumi
import pulumi_pulumiservice
from pulumi import ResourceOptions

pulumi_org = pulumi.get_organization()

# 3.152.0: prints stack's org
# 3.153.0: prints `None`
print("---", pulumi_org, "---")

pulumi_project = pulumi.get_project()

drive_webhook = pulumi_pulumiservice.Webhook(
    "drive-webhook",
    active=True,
    display_name=f"Drive 001",
    organization_name=pulumi_org,
    project_name=pulumi_project,
    stack_name="dev",
    payload_url=f"https://www.pulumi.com/drive?key=abcde",
    opts=ResourceOptions(retain_on_delete=True),
)
```

---

```
# pulumi version
v3.152.0
(.venv) ~/Documents/scratch/aws-py-scratch git:[main]
# pulumi preview
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/team-ce/py-scratch/dev/previews/45d51b67-d6b1-4609-8447-8d08414618b2

     Type                            Name            Plan       Info
 +   pulumi:pulumi:Stack             py-scratch-dev  create     1 message
 +   └─ pulumiservice:index:Webhook  drive-webhook   create     

Diagnostics:
  pulumi:pulumi:Stack (py-scratch-dev):
    --- team-ce ---
```

---

```
# pulumi version
v3.153.0
(.venv) ~/Documents/scratch/aws-py-scratch git:[main]
# pulumi preview
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/team-ce/py-scratch/dev/previews/303f2e28-4967-4c2e-adfe-0b2540b02176

     Type                 Name            Plan       Info
 +   pulumi:pulumi:Stack  py-scratch-dev  create     1 error; 1 message

Diagnostics:
  pulumi:pulumi:Stack (py-scratch-dev):
    --- None ---

    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/rsmith/Documents/scratch/aws-py-scratch/__main__.py", line 17, in <module>
        drive_webhook = pulumi_pulumiservice.Webhook(
            "drive-webhook",
        ...<6 lines>...
            opts=ResourceOptions(retain_on_delete=True),
        )
      File "/Users/rsmith/Documents/scratch/aws-py-scratch/.venv/lib/python3.13/site-packages/pulumi_pulumiservice/webhook.py", line 271, in __init__
        __self__._internal_init(resource_name, *args, **kwargs)
        ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/rsmith/Documents/scratch/aws-py-scratch/.venv/lib/python3.13/site-packages/pulumi_pulumiservice/webhook.py", line 309, in _internal_init
        raise TypeError("Missing required property 'organization_name'")
    TypeError: Missing required property 'organization_name'

Resources:
    + 1 to create
```

### Output of `pulumi about`

```
pulumi about
CLI          
Version      3.153.0
Go Version   go1.24.0
Go Compiler  gc

Plugins
KIND      NAME           VERSION
resource  aws            6.69.0
resource  aws-native     1.24.0
resource  command        1.0.1
resource  pulumiservice  0.29.0
language  python         3.153.0

Host     
OS       darwin
Version  15.3.1
Arch     arm64

This project is written in python: executable='/Users/rsmith/Documents/scratch/aws-py-scratch/.venv/bin/python' version='3.13.2'

Current Stack: team-ce/py-scratch/dev

Found no resources associated with dev

Found no pending operations associated with dev

Dependencies:
NAME                  VERSION
pulumi_aws            6.69.0
pulumi_aws_native     1.24.0
pulumi_command        1.0.1
pulumi_pulumiservice  0.29.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
From Rob, `pulumi about -t` shows:

```
Dependencies:
NAME                  VERSION
Arpeggio              2.0.2
attrs                 25.1.0
debugpy               1.8.12
dill                  0.3.9
grpcio                1.66.2
parver                0.5
pip                   24.3.1
protobuf              4.25.6
pulumi                3.147.0
pulumi_aws            6.69.0
pulumi_aws_native     1.24.0
pulumi_command        1.0.1
pulumi_pulumiservice  0.29.0
PyYAML                6.0.2
semver                2.13.0
six                   1.17.0
```

So this is using v3.147.0 of the `pulumi` python SDK. Works with v3.152.0 of the CLI, but doesn't with v3.153.0.

**Comment by justinvp** [comment]
The problem was introduced by https://github.com/pulumi/pulumi/pull/18595

Specifically, this line:

https://github.com/pulumi/pulumi/blob/4ae119c9439af4115628c6f309e959f477b09d62/sdk/python/cmd/pulumi-language-python-exec#L101

`pulumi-language-python-exec` ships with the CLI. It loads the user's `pulumi` module, which may be an older version. It does this:

https://github.com/pulumi/pulumi/blob/4ae119c9439af4115628c6f309e959f477b09d62/sdk/python/cmd/pulumi-language-python-exec#L94-L115

In `pulumi` python SDK versions prior to v3.153.0, the `pulumi.runtime.Settings` class doesn't have a `root_directory` arg. When we try to set it for an SDK version that doesn't support the arg, a `TypeError` is raised:

```
Settings.__init__() got an unexpected keyword argument 'root_directory'
```

We catch the error and fallback to some default values, but it means the `organization` is not set, so it is `None`.

The whole catch and fallback to default values was actually introduced when we added support for the `organization` in https://github.com/pulumi/pulumi/pull/10504, for older SDKs that didn't support an `organization` arg on `Settings`.

We should fix this to instead inspect the supported args on `Settings`. And only pass `root_directory` and `organization` if `Settings` supports those args. In the future, if we need to pass any additional new data, it can follow the same pattern to avoid breaking when older SDKs are in use.
