### ISSUE TITLE
[sdk/go] `WithMocks` regressed in v3.172.0

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#19682]
https://github.com/pulumi/pulumi/pull/19589 introduced a breaking change to the `MockResourceMonitor` interface in the Go SDK, adding a new method to the interface, which breaks existing implementations of the interface.

All existing users of `WithMocks` are broken when upgrading to v3.172.0; they'll have to implement the new method that was added to the interface.

A non-breaking approach would be to introduce a new interface for the method, and allow users to optionally implement it.

Found via https://github.com/pulumi/pulumi-yaml/pull/805, which shows the breaking change:

```go
	err := pulumi.RunErr(func(ctx *pulumi.Context) error {
		// ...
	}, pulumi.WithMocks(testProject, "dev", mocks))
```

> cannot use mocks (variable of type *testMonitor) as pulumi.MockResourceMonitor value in argument to pulumi.WithMocks: *testMonitor does not implement pulumi.MockResourceMonitor (missing method MethodCall)

**Comment by justinvp** [comment]
- Revert: https://github.com/pulumi/pulumi/pull/19683
- Release Freeze (containing the revert): https://github.com/pulumi/pulumi/pull/19684

**Comment by justinvp** [comment]
Closing as fixed since we reverted and released the revert. Opened https://github.com/pulumi/home/issues/4166 for the postmortem.
