### ISSUE TITLE
Python SDK 3.258.0 regression: Resource objects returned from Mocks.new_resource serialize as plain id strings instead of resource references

### ISSUE THREAD

**Issue by AdnanAvdagic** [pulumi/pulumi#24364]
## What happened?

Since pulumi 3.258.0, when a `pulumi.runtime.Mocks.new_resource` implementation returns a `Resource` object inside the mocked state (a common pattern for mocking component outputs such as `awsx.ecs.EC2TaskDefinition.task_definition`), that resource is serialized as its plain **id string** instead of a resource reference. It therefore never rehydrates on the consuming side, and any attribute lift on the dependent Output fails:

```
AttributeError: 'str' object has no attribute 'family'
  .venv/lib/python3.12/site-packages/pulumi/output.py:404: AttributeError
```

Works on 3.256.0 and 3.257.0; fails on 3.258.0. Nothing in the 3.258.0 changelog indicates an intentional behavior change for mocks.

## Example

```python
import json

import pulumi


class Mocks(pulumi.runtime.Mocks):
    def new_resource(self, args: pulumi.runtime.MockResourceArgs):
        import pulumi_aws as aws

        if args.typ == "awsx:ecs:EC2TaskDefinition":
            # Mock the component's resource-typed output with a real resource,
            # as suggested by the unit-testing docs' mocking pattern.
            return [
                args.name + "_id",
                dict(
                    args.inputs,
                    task_definition=aws.ecs.TaskDefinition(
                        f"{args.name}-td",
                        family=args.name,
                        container_definitions=json.dumps([]),
                    ),
                ),
            ]
        return [args.name + "_id", args.inputs]

    def call(self, args: pulumi.runtime.MockCallArgs):
        return {}


pulumi.runtime.set_mocks(Mocks(), preview=False)

import pulumi_awsx as awsx  # noqa: E402


@pulumi.runtime.test
def test_task_definition_rehydrates():
    td = awsx.ecs.EC2TaskDefinition(
        "svc",
        containers={
            "app": awsx.ecs.TaskDefinitionContainerDefinitionArgs(
                name="app",
                image="busybox",
            ),
        },
    )

    def check(family):
        assert family == "svc", f"expected 'svc', got {family!r}"

    return td.task_definition.family.apply(check)
```

Run with `pytest` against pulumi-aws 7.42.0 / pulumi-awsx 3.8.0:

- pulumi==3.257.0: passes
- pulumi==3.258.0: `AttributeError: 'str' object has no attribute 'family'` (the output resolved to `'svc-td_id'`, the mocked child's id string)

## Root cause analysis

3.258.0 refactored `monitor_supports_feature` (sdk/python/lib/pulumi/runtime/settings.py) from an async, per-feature RPC against the monitor (cached in `SETTINGS.feature_support`):

```python
# 3.257.0
async def monitor_supports_feature(feature: str) -> bool:
    if feature not in SETTINGS.feature_support:
        monitor = SETTINGS.monitor
        ...
```

to a synchronous read of a feature set:

```python
# 3.258.0
def monitor_supports_feature(feature: int) -> bool:
    return feature in SETTINGS.monitor_features
```

`Settings.monitor_features` is a `@contextproperty` (ContextVar-backed). `set_mocks` populates it in the **calling** context:

```python
# runtime/mocks.py (3.258.0)
monitor = MockMonitor(mocks) if monitor is None else monitor
monitor_features = set(monitor.GetDeploymentInfo(empty_pb2.Empty()).supportedFeatures)
settings = MockSettings(monitor=monitor, monitor_features=monitor_features, ...)
```

However, `MockMonitor.RegisterResource` serializes the state returned by the user's mock via `_sync_await(rpc.serialize_properties(state, {}))`, and that call appears to execute in a context where the ContextVar is unset, so `monitor_features` evaluates to the empty default. `serialize_property` then takes the no-resource-references branch:

```python
# runtime/rpc.py (3.258.0), ~line 487
if settings.monitor_supports_feature(
    resource_pb2.RESOURCE_MONITOR_FEATURE_RESOURCE_REFERENCES
):
    ...  # serialize as { _special_resource_sig, urn, id }  <-- not taken anymore
# Otherwise, serialize the resource as either its ID ... or its URN
return await serialize_property(resource_id if is_custom else resource.urn, ...)
```

so the resource is sent as its bare id string, `deserialize_resource` is never involved, and the consuming Output resolves to a `str`.

Under 3.257.0 the feature check asked the monitor directly (MockMonitor answers `hasSupport=True` for everything except `outputValues`), which worked regardless of thread/context — hence no issue there.

## Workaround

Patch the feature lookup after `set_mocks` to answer from the mock monitor's own advertised feature list:

```python
from google.protobuf import empty_pb2
from pulumi.runtime import settings as pulumi_settings

pulumi.runtime.set_mocks(mocks, ...)

features = set(
    pulumi_settings.SETTINGS.monitor.GetDeploymentInfo(
        empty_pb2.Empty()
    ).supportedFeatures
)
pulumi_settings.monitor_supports_feature = lambda feature: feature in features
```

Verified: the example above passes on 3.258.0 with this patch applied.

## Environment

- pulumi (Python SDK) 3.258.0 (regression introduced here; 3.256.0 and 3.257.0 OK)
- pulumi-aws 7.42.0, pulumi-awsx 3.8.0
- Python 3.12; hit in a real test suite on both macOS and ubuntu-latest (GitHub Actions); the standalone example above verified on macOS

**Comment by julienp** [comment]
Ah sorry, I broke this in https://github.com/pulumi/pulumi/pull/24308. To fix this I think we should pass the context down to the threads used for `run_in_executor`, https://github.com/pulumi/pulumi/pull/24403
