### PR TITLE
[codegen/go] Fix generation of nested collection types and remove invalid args types

### PR DESCRIPTION
**Pull request by EvanBoyle**
# Description

https://github.com/pulumi/pulumi/pull/7059/files#diff-434bc124a144c56427b080a04745148c2798b7026c4c6416f68795ddd069a997R329-R418 introduced changes that generate what appear to be invalid collection types (`ArgsArray`, `ArgsArrayMap`, etc). 

The fix here is twofold:

1. Trim `Args` suffixes from the type names in nested collection type generation
2. Break nested collection type generation into two steps: collect and dedupe types, and generate types. 

Diffs for kubernetes and terraform based providers look clean. The failing downstream is azure native which is expected as there were some breaking changes to schema that will be corrected in https://github.com/pulumi/pulumi-azure-native/pull/1077

Fixes https://github.com/pulumi/pulumi/issues/7595

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
This makes sense to me but I don't have a ton of context on collection types in our Go SDK, so I'd love others to review.

Does this also fix compilation errors in aws-native and google-native? (see https://github.com/pulumi/pulumi/issues/7622)

**Comment by t0yv0** [comment]
Looks reasonable at a glance.

**Review by pgavlin — APPROVED** [review]
