### ISSUE TITLE
Stack failure during Pulumi update investigation initiated

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#16399]
### What happened?

Customer reports:

> Hi, one of our stack fails when updating pulumi fro 3.111.1 to 3.113.3 with 
> a stack trace trace which looks to be entirely pulumi-internal:

```
 error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/q479080/.pulumi/3.113.3/pulumi/pulumi-language-python-exec", line 191, in <module>
        loop.run_until_complete(coro)
      File "/Users/q479080/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
        return future.result()
               ^^^^^^^^^^^^^^^
      File "/Users/q479080/cc/deploy-ci/.venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 132, in run_in_stack
        await run_pulumi_func(run)
      File "/Users/q479080/cc/deploy-ci/.venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 53, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/q479080/cc/deploy-ci/.venv/lib/python3.11/site-packages/pulumi/runtime/stack.py", line 109, in wait_for_rpcs
        await task
      File "/Users/q479080/cc/deploy-ci/.venv/lib/python3.11/site-packages/pulumi/output.py", line 197, in run
        transformed: Input[U] = func(value)
                                ^^^^^^^^^^^
      File "/Users/q479080/cc/deploy-ci/.venv/lib/python3.11/site-packages/pulumi/output.py", line 247, in lift
        return UNKNOWN if isinstance(v, Unknown) else getattr(v, item)
                                                      ^^^^^^^^^^^^^^^^
    AttributeError: 'str' object has no attribute '__fields__'
```

Also from the customer:

> Still fails with the same error on 3.116.1

### Example

If it helps, customer did a bisect and it spit out this commit as the culprit: 

https://github.com/pulumi/pulumi/commit/50eacf3c2f57ca6dae7ea88e49626e1ef413d815

Reproduction:

https://github.com/ederst/pulumi-in-a-pickle/tree/problem-with-pr15744

### Output of `pulumi about`

```
CLI
Version      3.113.3
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.27.0
resource  kubernetes  4.9.1
language  python      unknown
resource  random      4.16.1

Host
OS       darwin
Version  14.4.1
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
cc @Frassle to check if #15744 is related
