### ISSUE TITLE
Azure-Native Go SDK is broken after upgrading to 3.7.0

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#7595]
Unfortunately, we don't check this during PR build, so it's already merged (but not released yet). The nightly Go SDK Build job is failing with

```
# github.com/pulumi/pulumi-azure-native/sdk/go/azure/datafactory
go/azure/datafactory/pulumiTypes.go:149793:58: undefined: SSISExecutionParameterResponseArgsMapInput
# github.com/pulumi/pulumi-azure-native/sdk/go/azure/datamigration
go/azure/datamigration/pulumiTypes.go:26278:51: undefined: DatabaseTableResponseArgsArrayInput
# github.com/pulumi/pulumi-azure-native/sdk/go/azure/documentdb
go/azure/documentdb/pulumiTypes.go:17348:44: undefined: CompositePathResponseArgsArrayInput
# github.com/pulumi/pulumi-azure-native/sdk/go/azure/insights
go/azure/insights/pulumiTypes.go:22991:62: undefined: WorkbookTemplateLocalizedGalleryArgsArrayInput
# github.com/pulumi/pulumi-azure-native/sdk/go/azure/webpubsub
go/azure/webpubsub/pulumiTypes.go:4653:58: undefined: EventHandlerTemplateResponseArgsArrayInput
```

See https://github.com/pulumi/pulumi-azure-native/runs/3116673664?check_suite_focus=true#step:16:27
