### ISSUE TITLE
Flaky test: TempDir RemoveAll cleanup: [...] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#19010]
Test flake on Windows:

https://github.com/pulumi/pulumi/actions/runs/14042855676/job/39317279602?pr=19009#step:41:212

```
=== FAIL: . TestLanguageImportSmoke/python (23.95s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokepython2071463712\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestLanguageImportSmokepython2071463712/001
    environment.go:205: Running command pulumi new python --yes
    environment.go:205: Running command pulumi import --yes random:index/randomId:RandomId identifier p-9hUg
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestLanguageImportSmokepython2071463712\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokepython2071463712\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokepython2071463712\001\project: The process cannot access the file because it is being used by another process.

=== FAIL: . TestLanguageImportSmoke/java (22.31s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokejava3269083010\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestLanguageImportSmokejava3269083010/001
    environment.go:205: Running command pulumi new java --yes
    environment.go:205: Running command pulumi import --yes random:index/randomId:RandomId identifier p-9hUg
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestLanguageImportSmokejava3269083010\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokejava3269083010\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokejava3269083010\001\project: The process cannot access the file because it is being used by another process.

=== FAIL: . TestLanguageImportSmoke/go (12.14s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokego1417502556\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestLanguageImportSmokego1417502556/001
    environment.go:205: Running command pulumi new go --yes
    environment.go:205: Running command pulumi import --yes random:index/randomId:RandomId identifier p-9hUg
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestLanguageImportSmokego1417502556\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokego1417502556\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokego1417502556\001\project: The process cannot access the file because it is being used by another process.

=== FAIL: . TestLanguageImportSmoke/yaml (5.60s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokeyaml2636839738\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestLanguageImportSmokeyaml2636839738/001
    environment.go:205: Running command pulumi new yaml --yes
    environment.go:205: Running command pulumi import --yes random:index/randomId:RandomId identifier p-9hUg
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestLanguageImportSmokeyaml2636839738\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokeyaml2636839738\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokeyaml2636839738\001\project: The process cannot access the file because it is being used by another process.

=== FAIL: . TestLanguageImportSmoke/nodejs (38.33s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokenodejs3670192228\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestLanguageImportSmokenodejs3670192228/001
    environment.go:205: Running command pulumi new typescript --yes
    environment.go:205: Running command pulumi import --yes random:index/randomId:RandomId identifier p-9hUg
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestLanguageImportSmokenodejs3670192228\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokenodejs3670192228\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokenodejs3670192228\001\project: The process cannot access the file because it is being used by another process.

=== FAIL: . TestLanguageImportSmoke/dotnet (15.84s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokedotnet669506834\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestLanguageImportSmokedotnet669506834/001
    environment.go:205: Running command pulumi new csharp --yes
    environment.go:205: Running command pulumi import --yes random:index/randomId:RandomId identifier p-9hUg
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestLanguageImportSmokedotnet669506834\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokedotnet669506834\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestLanguageImportSmokedotnet669506834\001\project: The process cannot access the file because it is being used by another process.

=== FAIL: . TestLanguageImportSmoke (118.17s)

=== FAIL: . TestImportVersionSmoke (10.95s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestImportVersionSmoke665381590\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestImportVersionSmoke665381590/001
    environment.go:205: Running command pulumi new D:\a\pulumi\pulumi\tests\testdata\random_go --yes
    environment.go:205: Running command pulumi plugin install resource random 4.16.7
    environment.go:205: Running command pulumi plugin install resource random 4.13.0
    environment.go:205: Running command pulumi import --yes random:index/randomId:RandomId identifier p-9hUg
    environment.go:205: Running command pulumi stack export
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestImportVersionSmoke665381590\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestImportVersionSmoke665381590\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestImportVersionSmoke665381590\001\project: The process cannot access the file because it is being used by another process.

=== FAIL: . TestImportParameterizedSmoke (44.51s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestImportParameterizedSmoke4206137889\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestImportParameterizedSmoke4206137889/001
    environment.go:205: Running command pulumi new D:\a\pulumi\pulumi\tests\testdata\random_python --yes
    environment.go:205: Running command pulumi plugin install resource terraform-provider 0.3.1
    environment.go:205: Running command pulumi package add terraform-provider hashicorp/random 3.6.3
    environment.go:205: Running command pulumi install
    environment.go:205: Running command pulumi up --yes
    environment.go:205: Running command pulumi import --yes random:index/id:Id identifier p-9hUg
    environment.go:205: Running command pulumi stack export
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestImportParameterizedSmoke4206137889\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestImportParameterizedSmoke4206137889\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestImportParameterizedSmoke4206137889\001\project: The process cannot access the file because it is being used by another process.

=== FAIL: . TestImportParameterizedSmokeFreshState (37.14s)
    environment.go:85: Created new test environment:  C:\Users\RUNNER~1\AppData\Local\Temp\TestImportParameterizedSmokeFreshState875474990\001
    environment.go:205: Running command pulumi login --cloud-url file://C:/Users/RUNNER~1/AppData/Local/Temp/TestImportParameterizedSmokeFreshState875474990/001
    environment.go:205: Running command pulumi new D:\a\pulumi\pulumi\tests\testdata\random_python --yes
    environment.go:205: Running command pulumi plugin install resource terraform-provider 0.3.1
    environment.go:205: Running command pulumi package add terraform-provider hashicorp/random 3.6.3
    environment.go:205: Running command pulumi install
    environment.go:205: Running command pulumi import --yes random:index/id:Id identifier p-9hUg
    environment.go:205: Running command pulumi stack export
    history_test.go:28: error cleaning up test directory "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\TestImportParameterizedSmokeFreshState875474990\\001": remove C:\Users\RUNNER~1\AppData\Local\Temp\TestImportParameterizedSmokeFreshState875474990\001\project: The process cannot access the file because it is being used by another process.
    testing.go:1267: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestImportParameterizedSmokeFreshState875474990\001\project: The process cannot access the file because it is being used by another process.
```

**Comment by Frassle** [comment]
I wonder if this is plugins not shutting down cleanly?

**Comment by justinvp** [comment]
Seems like this was introduced with #18952, which changed `NewEnvironment` to use `t.TempDir()`:

https://github.com/pulumi/pulumi/blob/2ae585f5d6bd790f8bc3ca76825a54f8f320d24a/sdk/go/common/testing/environment.go#L77-L92

`t.TempDir()` automatically deletes the dir after the test is complete.

Either we revert the change for `NewEnvironment` or we need to rethink the helpers for deleting the environment. One additional downside to using `t.TempDir` is it sounds like we may have lost a "feature" where the temp dir isn't deleted if the test fails. Sounds like the `t.TempDir` dir is always deleted.

**Comment by Frassle** [comment]
Sounds reasonable to just revert the change for NewEnvironment
