### ISSUE TITLE
Possible Python SDK regression in 3.38.0: module 'pulumi.runtime.settings' has no attribute '_set_test_mode_enabled'

### ISSUE THREAD

**Issue by jlgoolsbee** [pulumi/pulumi#10549]
### What happened?

After upgrade to 3.38.0, actions like `pulumi up` and `pulumi preview` are failing with the following stacktrace:

```
$ pulumi up
Previewing update ([...]):
     Type                 Name                Plan     Info
     pulumi:pulumi:Stack  [...]                        1 error
 
Diagnostics:
  pulumi:pulumi:Stack ([...]):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 111, in <module>
        loop.run_until_complete(coro)
      File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
        return future.result()
      File "/usr/local/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/local/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        func()
      File "/usr/local/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 126, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/usr/local/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 149, in __init__
        func()
      File "/usr/local/bin/pulumi-language-python-exec", line 110, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/usr/local/lib/python3.10/runpy.py", line 289, in run_path
        return _run_module_code(code, init_globals, run_name,
      File "/usr/local/lib/python3.10/runpy.py", line 96, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "__main__.py", line 14, in <module>
        pulumi.runtime.settings._set_test_mode_enabled(True)
    AttributeError: module 'pulumi.runtime.settings' has no attribute '_set_test_mode_enabled'
```

Rolling back just the Python SDK to 3.37.2 (`pip install pulumi==3.37.2`) even with CLI still at 3.38.0 seems to resolve the issue (previews and updates are successful).

### Steps to reproduce

1. Have a python 3.10.6 environment
2. Have latest pulumi client and python SDK (3.38.0) installed
3. Run `pulumi preview` or `pulumi up` on a stack

### Expected Behavior

Successful execution of the requested action.

### Actual Behavior

Failed execution of the requested action with stacktrace above.

### Output of `pulumi about`

```
# pulumi about
CLI          
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.13.0
aws-native  0.22.0
command     0.4.1
kubernetes  3.21.0
postgresql  3.6.0
python      unknown
random      4.8.0

Host     
OS       debian
Version  11.4
Arch     x86_64

This project is written in python: executable='/usr/local/bin/python3' version='3.10.6'

Backend        
Name           [...]
URL            [...]
User           [...]
Organizations  

Dependencies:
NAME               VERSION
backoff            2.1.2
black              22.6.0
boto3              1.24.22
coloredlogs        15.0.1
debugpy            1.6.0
Jinja2             3.1.2
kubernetes         23.6.0
mergedeep          1.3.4
packaging          21.3.0
pip                22.2.1
pre-commit         2.20.0
pulumi-aws         5.13.0
pulumi-aws-native  0.22.0
pulumi-command     0.4.1
pulumi-kubernetes  3.21.0
pulumi-postgresql  3.6.0
pulumi-random      4.8.0
pyhumps            3.7.2
wheel              0.37.1
```

### Additional context

We do not make use of the associated "test mode" or environment variable `PULUMI_TEST_MODE`, which are the only references I could find to the error itself.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
some extra context
- https://github.com/pulumi/pulumi/issues/3045

PR:
- https://github.com/pulumi/pulumi/pull/10400

**Comment by jlgoolsbee** [comment]
Oh geez – you are correct – I'm so sorry! 🤦 

I _swear_ I searched for this exact string (and the related env var) in our repo several times before going down this route, so my apologies for the obvious miss here – removing those calls indeed resolves the issue.

**Comment by dixler** [comment]
> Oh geez – you are correct – I'm so sorry! 🤦 
> 
> 
> 
> I _swear_ I searched for this exact string (and the related env var) in our repo several times before going down this route, so my apologies for the obvious miss here – removing those calls indeed resolves the issue.
> 
> 

No worries. Feedback helps us get better and understand usage given our constraints of being a locally run tool.
