### ISSUE TITLE
[Go] Enum Ptr Input type not defined

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi#10097]
### What happened?

Upgrading codegen in azure-native from `v3.34.0` to `v3.35.3` fails to produce a buildable Go SDK.

Properties were previously defined with a type named like `[NAME]EnumPtrInput` are changed to `[NAME]PtrInput` which is not defined. 

This may be specific to azure-native because we set the following Go language settings:

```json
        "go": {
            "disableInputTypeRegistrations": true,
            "generateResourceContainerTypes": false,
```

### Steps to reproduce

1. Upgrade azure-native codegen to use pulumi/pulumi pkg v3.35.3
2. Generate Go SDK
3. Go is unable to compile

### Expected Behavior

Either the non-enum named types need to be defined, or the type reference should revert back to include 'Enum' in the name.

### Actual Behavior

```
Error: go/azure/apimanagement/product.go:169:8: undefined: ProductStatePtrInput
Error: go/azure/apimanagement/subscription.go:202:8: undefined: SubscriptionStatePtrInput
...
```

https://github.com/pulumi/pulumi-azure-native/runs/7299044555?check_suite_focus=true#step:17:62

### Versions used

v3.35.3

### Additional context

The impact of this bug is that we can't upgrade to the latest version of pulumi/pulumi in azure-native which means we can't integrate the fix for deeply nested array types.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
This regression was introduced in https://github.com/pulumi/pulumi/pull/9920, and was fixed in https://github.com/pulumi/pulumi/pull/9933. It is already fixed in master.
