### ISSUE TITLE
Azure provider Go SDK fails to compile cdn module

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi#11630]
### What happened?

After upgrading tf-bridge to v3.34.0 and pulumi/sdk/v3 to 3.48.1 in pulumi-azure and regenerating the Go SDK, it fails to compile.

```
cd sdk && go list `grep -e "^module" go.mod | cut -d ' ' -f 2`/go/... | xargs go build
# github.com/pulumi/pulumi-azure/sdk/v5/go/azure/cdn
go/azure/cdn/frontdoorCustomEndpoint.go:125:6: undefined: FrontdoorCustomEndpointTlsOutput
go/azure/cdn/frontdoorCustomEndpoint.go:143:17: invalid operation: args.Tls == nil (operator == not defined on untyped nil)
go/azure/cdn/frontdoorCustomEndpoint.go:181:7: undefined: FrontdoorCustomEndpointTls
go/azure/cdn/frontdoorCustomEndpoint.go:200:6: undefined: FrontdoorCustomEndpointTlsPtrInput
go/azure/cdn/frontdoorCustomEndpoint.go:221:6: undefined: FrontdoorCustomEndpointTls
go/azure/cdn/frontdoorCustomEndpoint.go:237:6: undefined: FrontdoorCustomEndpointTlsInput
go/azure/cdn/frontdoorCustomEndpoint.go:358:46: undefined: FrontdoorCustomEndpointTlsOutput
go/azure/cdn/frontdoorCustomEndpoint.go:359:51: undefined: FrontdoorCustomEndpointTlsOutput
make: *** [build_go] Error 1
```

### Steps to reproduce

```
git checkout master && git pull
cd provider
go get -u -v github.com/pulumi/pulumi-terraform-bridge/v3
cd ..
make
```

### Expected Behavior

Compilation succeeds

### Actual Behavior

see above

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
The build error is caused by a breaking change upstream. `pulumi-azure` no longer emits the file `sdk/go/azure/cdn/frontdoorCustomEndpoint.go`, but since it is not removed, it still shows up during compilation tests. That is what causes the dangling reference. The following sequence builds:
```sh
git checkout master && git pull
(cd provider && go get -u -v github.com/pulumi/pulumi-terraform-bridge/v3)
rm sdk/go
make
```

**Comment by iwahbe** [comment]
I have opened https://github.com/pulumi/action-test-provider-downstream/pull/14 to address the issue for downstream tests.

**Comment by thomas11** [comment]
@danielrbradley looks like we need to make sure the Makefile cleans the SDK folder correctly before generating new SDKs

**Comment by danielrbradley** [comment]
@thomas11 we do according to the makefile - we always delete the whole SDK before every generate...

https://github.com/pulumi/pulumi-azure-native/blob/master/Makefile#L234

Maybe there's something else at play here 🤔

**Comment by thomas11** [comment]
@danielrbradley that's the native provider but this issue is in the bridged one which simply builds.
https://github.com/pulumi/pulumi-azure/blob/master/Makefile#L41

**Comment by thomas11** [comment]
@danielrbradley pulumi/pulumi-azure#1160 is the reason we cannot just `make clean` before building currently.

**Comment by danielrbradley** [comment]
Oh ... my misreading (I do that a lot)! Yes I guess we should probably call `make clean` as a temporary workaround. Also, I think I fixed this in the new version of the makefile, but we've just not rolled it out yet 😞

**Comment by alextrs** [comment]
@thomas11 we see the same issue after upgrading from pulumi azure v4.11.0 to v5.27.0. Tried with: 
```
github.com/pulumi/pulumi-azure/sdk/v5 v5.27.0
github.com/pulumi/pulumi/sdk/v3 v3.50.1
```

**Comment by thomas11** [comment]
@alextrs the issue is not fixed yet in pulumi/pulumi-azure. Above, [Ian showed a workaround](https://github.com/pulumi/pulumi/issues/11630#issuecomment-1348182966) - does it work for you?
