### ISSUE TITLE
Cannot build with `pkg` at `v3.181.0`

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#19981]
### What happened?

Something went wrong with the release of `pkg` for `v3.181.0`. Attempting to build a go program with it fails with compile errors in `client`.

### Example

Given the following go program:

```go
package main

import (
	"github.com/pulumi/pulumi/pkg/v3/backend/httpstate/client"
)

func main() {
	_ = client.NewClient("", "", false, nil)
}
```

It fails to compile:
```
go build . 
# github.com/pulumi/pulumi/pkg/v3/backend/httpstate/client
../../../../go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.181.0/backend/httpstate/client/client.go:1684:12: undefined: apitype.TemplateMetadata
../../../../go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.181.0/backend/httpstate/client/client.go:1690:19: undefined: apitype.TemplateMetadata
../../../../go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.181.0/backend/httpstate/client/client.go:1729:86: undefined: apitype.TemplateMetadata
../../../../go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.181.0/backend/httpstate/client/client.go:1736:29: undefined: apitype.TemplateMetadata
../../../../go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.181.0/backend/httpstate/client/client.go:1742:21: undefined: apitype.ListTemplatesResponse
../../../../go/pkg/mod/github.com/pulumi/pulumi/pkg/v3@v3.181.0/backend/httpstate/client/client.go:1745:15: undefined: apitype.TemplateMetadata
```

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by julienp** [comment]
```
* 49f2764621 - (tag: pkg/v3.181.0) Changelog and go.mod updates for v3.181.0 (#19970) (3 days ago) <Pulumi Bot>
* f6d7085d08 - Add `(registry.Registry).{Get,List}Template(s)` (#19937) (3 days ago) <Ian Wahbe>
* 27bcc48e46 - Add a warning to the `CONTRIBUTING.md` release section (#19967) (3 days ago) <Tom Harding>
* 520a0398f5 - Freeze v3.181.0 (#19968) (3 days ago) <Julien>
* c53ffb7ac4 - (tag: v3.181.0, tag: sdk/v3.181.0) Bump to 3.181 (#19966) (3 days ago) <Fraser Waters>
```

`sdk` 3.181 doesn't have those new API types, but `pkg` was tagged after they were merged

Locally in pu/pu and in CI, we probably have a replace of `sdk`, so it's fine, but outside of pu/pu it will pick the released 3.181 version.

**Comment by lunaris** [comment]
Given this, I think the only fix will be to go straight to 3.182.0 unfortunately, though this is yet another gotcha of the non-atomicity of tagging `pkg` and `sdk` -- closing this out.
